// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using strivolabs_Assessment.Data;

#nullable disable

namespace strivolabs_Assessment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("strivolabs_Assessment.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 18, 19, 34, 3, 729, DateTimeKind.Utc).AddTicks(2978),
                            PasswordHash = "$2a$11$tr15Zt8qUvb7aEq2FQb77.PhiFZy5ilPhx/oxwnxRhSwnfLwAVxuW",
                            ServiceId = "Naija_PROMO_001"
                        });
                });

            modelBuilder.Entity("strivolabs_Assessment.Entities.ServiceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ServiceTokens");
                });

            modelBuilder.Entity("strivolabs_Assessment.Entities.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscribedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UnsubscribedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "PhoneNumber")
                        .IsUnique();

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("strivolabs_Assessment.Entities.ServiceToken", b =>
                {
                    b.HasOne("strivolabs_Assessment.Entities.Service", "service")
                        .WithMany("Tokens")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("service");
                });

            modelBuilder.Entity("strivolabs_Assessment.Entities.Subscriber", b =>
                {
                    b.HasOne("strivolabs_Assessment.Entities.Service", "Service")
                        .WithMany("Subscribers")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("strivolabs_Assessment.Entities.Service", b =>
                {
                    b.Navigation("Subscribers");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
